# Generated by Django 3.1.3 on 2020-11-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit', models.TextField()),
                ('Price', models.TextField()),
                ('Description', models.TextField()),
                ('Occupied', models.BooleanField()),
                ('Tenant_Name', models.TextField(default='Unoccupied')),
            ],
        ),
    ]
