# Generated by Django 3.1.3 on 2020-11-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit', models.CharField(max_length=7)),
                ('Price', models.FloatField(default=799.0)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Occupied', models.BooleanField(default=False)),
                ('Tenant_Name', models.TextField(default='Unoccupied')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=16)),
                ('Bill', models.IntegerField(default=0)),
                ('TenantName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=16, null=True)),
                ('Last_Name', models.CharField(max_length=16, null=True)),
                ('Unit', models.CharField(max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue', models.TextField()),
                ('Resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
