# Generated by Django 3.1.3 on 2020-11-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0002_auto_20201111_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='apartment',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='Unit',
            field=models.CharField(max_length=7),
        ),
    ]
