# Generated by Django 3.1.3 on 2020-11-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0004_auto_20201121_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('SSN', models.CharField(max_length=9)),
                ('Username', models.TextField()),
                ('Password', models.CharField(max_length=9)),
            ],
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
