# Generated by Django 3.1.3 on 2020-11-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0005_auto_20201122_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='Bill',
            field=models.IntegerField(default=0),
        ),
    ]
