# Generated by Django 3.1.3 on 2020-11-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0007_workorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='First_Name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='Last_Name',
            field=models.TextField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='Password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='SSN',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='Username',
            field=models.TextField(blank=True, max_length=16, null=True),
        ),
    ]
