# Generated by Django 3.1.3 on 2020-11-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0008_auto_20201123_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='First_Name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='Last_Name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='Password',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='SSN',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='Username',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
