# Generated by Django 3.1.3 on 2020-11-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0009_auto_20201124_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
